# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 92bbb7513d0571234ead5308c7f7a33af33c65a43dc4ac0d00b2d0d76170c47065638c248025999b084c820798c4f7b6619155292258770ff45da152090cdeeb

test:
  secret_key_base: 4cef23200416388766a048d3ee0c0da5e50e656c1fd46e181065165997364c39f29b878f9e1e29c114c86a49605f668b73f3b7256ce64ab8535f8de5513028b8

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
